# Generated by Django 3.1.7 on 2021-05-11 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
