# Generated by Django 3.1.7 on 2021-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210511_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
